#!/bin/sh

userresources=$HOME/.config/X11/Xresources

# merge in defaults and keymaps

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# start some nice programs
picom &
pulseaudio &
xroot-status-restart &
ssh-add-defaults &
dbus-launch startdwm
