#!/bin/sh

userresources=$HOME/.config/X11/Xresources

# merge in defaults and keymaps
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# start some nice programs
picom &
sleep 5 && pulseaudio &
escapecaps &
sleep 5 && xroot-status-restart &
ssh-add-defaults &
dbus-launch startdwm
