# Alacritty Configuration
# Based on st config from https://github.com/norpie/st
# Colors from catppuccin-mocha

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 0, y = 0 }
decorations = "none"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Alacritty"
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 5000
multiplier = 3

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 11.771

[font.offset]
x = 1
y = 0

[cursor]
style = { shape = "Block", blinking = "Off" }
thickness = 0.15

[terminal.shell]
program = "/usr/bin/env"
args = ["zsh"]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[keyboard]
bindings = [
    # Copy/Paste
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    
    # Font size
    { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control|Shift", action = "ResetFontSize" },
    
    # Scrollback
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", action = "ScrollToTop" },
    { key = "End", mods = "Shift", action = "ScrollToBottom" },
]

# Catppuccin Mocha theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[terminal]
